version: "3"

services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
    was:
        build: .
        image: shoeguard-main
        restart: always
        ports:
            - "8080:80"
        environment:
            PSQL_HOST: postgresql
